#!/bin/sh

set -e

COLOR_RED='\033[0;31m'          # Red
COLOR_GREEN='\033[0;32m'        # Green
COLOR_YELLOW='\033[0;33m'       # Yellow
COLOR_BLUE='\033[0;94m'         # Blue
COLOR_PURPLE='\033[0;35m'       # Purple
COLOR_OFF='\033[0m'             # Reset


version_sort() {
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sort.html
    # https://man.netbsd.org/NetBSD-8.1/i386/sort.1
    #
    # sort: unrecognized option: V
    # BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.
    # Usage: sort [-nrugMcszbdfiokt] [-o FILE] [-k start[.offset][opts][,end[.offset][opts]] [-t CHAR] [FILE]...
    if  printf '\n' | (sort -V > /dev/null 2>&1) ; then
        printf '%s\n' "$*" | tr ' ' '\n' | sort -V
    else
        printf '%s\n' "$*" | tr ' ' '\n' | sort -t. -n -k1,1 -k2,2 -k3,3 -k4,4
    fi
}

# check if match the condition
#
# condition:
# eq  equal
# ne  not equal
# gt  greater than
# lt  less than
# ge  greater than or equal
# le  less than or equal
#
# examples:
# version_match 1.15.3 eq 1.16.0
# version_match 1.15.3 lt 1.16.0
# version_match 1.15.3 gt 1.16.0
# version_match 1.15.3 le 1.16.0
# version_match 1.15.3 ge 1.16.0
version_match() {
    case $2 in
        eq)  [ "$1"  = "$3" ] ;;
        ne)  [ "$1" != "$3" ] ;;
        le)
            if [ "$1" = "$3" ] ; then
                return 0
            fi
            [ "$1" = "$(version_sort "$1" "$3" | head -n 1)" ]
            ;;
        ge)
            if [ "$1" = "$3" ] ; then
                return 0
            fi
            [ "$1" = "$(version_sort "$1" "$3" | tail -n 1)" ]
            ;;
        lt)
            if [ "$1" = "$3" ] ; then
                return 1
            fi
            [ "$1" = "$(version_sort "$1" "$3" | head -n 1)" ]
            ;;
        gt)
            if [ "$1" = "$3" ] ; then
                return 1
            fi
            [ "$1" = "$(version_sort "$1" "$3" | tail -n 1)" ]
            ;;
        *)  printf '%s\n' "version_compare: $2: not supported operator." >&2
            return 1
    esac
}

package_name_transform_from_uppm_to_brew() {
    case $1 in
        gm4)      printf '%s\n' 'm4'        ;;
        xxd)      printf '%s\n' 'vim'       ;;
        file)     printf '%s\n' 'file-formula' ;;
        gtar)     printf '%s\n' 'gnu-tar'   ;;
        gmake)    printf '%s\n' 'make'      ;;
        gindent)  printf '%s\n' 'gnu-indent';;
        xattr)    printf '%s\n' 'attr'      ;;
        patch)    printf '%s\n' 'gpatch'    ;;
        delta)    printf '%s\n' 'git-delta' ;;
        proj7)    printf '%s\n' 'proj@7'    ;;
        bsdtar)   printf '%s\n' 'libarchive';;
        blake3)   printf '%s\n' 'b3sum'     ;;
        utfcpp)   printf '%s\n' 'utf8cpp'   ;;
        tcl-core) printf '%s\n' 'tcl-tk'    ;;
        openpmix) printf '%s\n' 'pmix'      ;;
        xsltproc) printf '%s\n' 'libxslt'   ;;

        freetype2)printf '%s\n' 'freetype'  ;;
        freetype2-with-harfbuzz)
                  printf '%s\n' 'freetype'  ;;

        golang@1.21)
                  printf '%s\n' 'go@1.21'   ;;
        golang)   printf '%s\n' 'go'        ;;

        dot_static)
                  printf '%s\n' 'graphviz'  ;;

        glib-tools)
                  printf '%s\n' 'glib'      ;;

        gettext-tools)
                  printf '%s\n' 'gettext'   ;;
        gettext-runtime)
                  printf '%s\n' 'gettext'   ;;

        libmediainfo|mediainfo)
                  printf '%s\n' 'media-info';;

        libxml2-utils|libxml2-python3)
                  printf '%s\n' 'libxml2'   ;;

        libprotobuf)
                  printf '%s\n' 'protobuf'  ;;

        libsqlite3)printf '%s\n' 'sqlite'   ;;
        libpcre2) printf '%s\n' 'pcre2'     ;;
        libexpat) printf '%s\n' 'expat'     ;;
        libpcre)  printf '%s\n' 'pcre'      ;;
        libcurl)  printf '%s\n' 'curl'      ;;
        libwebp)  printf '%s\n' 'webp'      ;;
        libzstd)  printf '%s\n' 'zstd'      ;;
        liblzma)  printf '%s\n' 'xz'        ;;
        libopus)  printf '%s\n' 'opus'      ;;
        libuuid)  printf '%s\n' 'util-linux';;
        libz3.a)  printf '%s\n' 'z3'        ;;
        libgmp)   printf '%s\n' 'gmp'       ;;
        libbz2)   printf '%s\n' 'bzip2'     ;;
        libzmq)   printf '%s\n' 'zeromq'    ;;
        libjxl)   printf '%s\n' 'jpeg-xl'   ;;

        toml++)   printf '%s\n' 'tomlplusplus'  ;;

        xorg-*)   printf '%s\n' "$1" | cut -c6- ;;

        *)        printf '%s\n' "$1"
    esac
}

get_version_from_url() {
    basename "$1" | tr '_@' - | sed -e 's|\.tar\.[glx]z$||' -e 's|\.tar\.bz2$||' -e 's|\.t[glx]z$||' -e 's|\.zip$||' -e 's|-stable||' -e 's|-source||' -e 's|[-.]src$||' -e 's|\.orig||' | awk -F- '{print $NF}' | sed -e 's|^v||'
}

package_version() {
    PACKAGE_VERSION="$(sed -n '/^version:/p' formula/$1.yml | cut -c10-)"

    if [ -n "$PACKAGE_VERSION" ] ; then
        printf '%s\n' "$PACKAGE_VERSION"
        return 0
    fi

    PACKAGE_SRC_URL="$(sed -n '/^src-url:/p' formula/$1.yml | cut -c10-)"

    if [ -z "$PACKAGE_SRC_URL" ] ; then
        return 0
    else
        basename "$PACKAGE_SRC_URL" | tr '_@' - | sed -e 's|\.tar\.[glx]z$||' -e 's|\.tar\.bz2$||' -e 's|\.t[glx]z$||' -e 's|\.zip$||' -e 's|-stable||' -e 's|-source||' -e 's|[-.]src$||' -e 's|\.orig||' | awk -F- '{print $NF}' | sed -e 's|^v||'
    fi
}

main() {
    AVAILABLE_PACKAGE_NAMES="$(find formula -maxdepth 1 -type f -name '*.yml' -exec basename {} .yml \;)"

    for PACKAGE_NAME in $AVAILABLE_PACKAGE_NAMES
    do
        PACKAGE_VERSION="$(package_version "$PACKAGE_NAME")"

        BREW_PACKAGE_NMAE="$(package_name_transform_from_uppm_to_brew "$PACKAGE_NAME")"

        if brew info "$BREW_PACKAGE_NMAE" > /dev/null 2>&1 ; then
            BREW_PACKAGE_VERS=$(brew info "$BREW_PACKAGE_NMAE" --json | yq '.[0].versions.stable')

            if version_match "$BREW_PACKAGE_VERS" gt "$PACKAGE_VERSION" ; then
                printf "${COLOR_RED}%-10s %-10s  |  %-10s %-10s${COLOR_OFF}\n" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$BREW_PACKAGE_NMAE" "$BREW_PACKAGE_VERS"
            else
                :
                #printf "${COLOR_GREEN}%-10s %-10s  |  %-10s %-10s${COLOR_OFF}\n" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$BREW_PACKAGE_NMAE" "$BREW_PACKAGE_VERS"
            fi
        else
            printf "${COLOR_BLUE}%-10s %-10s  |${COLOR_OFF}\n" "$PACKAGE_NAME" "$PACKAGE_VERSION"
        fi
    done
}

main "$@"
