package set summary "Binary-decimal and decimal-binary routines for IEEE doubles"
package set src.git "https://github.com/google/double-conversion.git"
package set src.url "https://github.com/google/double-conversion/archive/v3.1.5.tar.gz"
package set src.sum "a63ecb93182134ba4293fd5f22d6e08ca417caafa244afaa751cbfddf6415b13"
package set license "BSD-3-Clause"
package set bsystem "cmake"
