package set summary "Asynchronous event library"
package set webpage "http://software.schmorp.de/pkg/libev.html"
package set version "4.33"
package set src.url "https://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/libe/libev/libev_${PACKAGE_VERSION}.orig.tar.gz"
package set src.sum "507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea"
package set bsystem "configure"
