#!/bin/sh

set -ex

COLOR_RED='\033[0;31m'          # Red
COLOR_GREEN='\033[0;32m'        # Green
COLOR_YELLOW='\033[0;33m'       # Yellow
COLOR_BLUE='\033[0;94m'         # Blue
COLOR_PURPLE='\033[0;35m'       # Purple
COLOR_OFF='\033[0m'             # Reset

run() {
    echo "${COLOR_PURPLE}==>${COLOR_OFF} ${COLOR_GREEN}$@${COLOR_OFF}"
    eval "$@"
}

version_sort() {
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sort.html
    # https://man.netbsd.org/NetBSD-8.1/i386/sort.1
    #
    # sort: unrecognized option: V
    # BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.
    # Usage: sort [-nrugMcszbdfiokt] [-o FILE] [-k start[.offset][opts][,end[.offset][opts]] [-t CHAR] [FILE]...
    if  printf '\n' | (sort -V > /dev/null 2>&1) ; then
        printf '%s\n' "$@" | sort -V
    else
        printf '%s\n' "$@" | sort -t. -n -k1,1 -k2,2 -k3,3 -k4,4
    fi
}

# check if match the condition
#
# condition:
# eq  equal
# ne  not equal
# gt  greater than
# lt  less than
# ge  greater than or equal
# le  less than or equal
#
# examples:
# version_match 1.15.3 eq 1.16.0
# version_match 1.15.3 lt 1.16.0
# version_match 1.15.3 gt 1.16.0
# version_match 1.15.3 le 1.16.0
# version_match 1.15.3 ge 1.16.0
version_match() {
    case $2 in
        eq)  [ "$1"  = "$3" ] ;;
        ne)  [ "$1" != "$3" ] ;;
        le)
            if [ "$1" = "$3" ] ; then
                return 0
            fi
            [ "$1" = "$(version_sort "$1" "$3" | head -n 1)" ]
            ;;
        ge)
            if [ "$1" = "$3" ] ; then
                return 0
            fi
            [ "$1" = "$(version_sort "$1" "$3" | tail -n 1)" ]
            ;;
        lt)
            if [ "$1" = "$3" ] ; then
                return 1
            fi
            [ "$1" = "$(version_sort "$1" "$3" | head -n 1)" ]
            ;;
        gt)
            if [ "$1" = "$3" ] ; then
                return 1
            fi
            [ "$1" = "$(version_sort "$1" "$3" | tail -n 1)" ]
            ;;
        *)  printf '%s\n' "version_compare: $2: not supported operator." >&2
            return 1
    esac
}

#########################################################################

git config --global user.name  leleliu008
git config --global user.email leleliu008@gmail.com

git clone https://github.com/leleliu008/xcpkg-formula-repository-official-core

#########################################################################

for FORMULA_FILEPATH_A in formula/*.yml
do
    : "################################################"

    FORMULA_FILEPATH_B="xcpkg-formula-repository-official-core/$FORMULA_FILEPATH_A"

    [ -L "$FORMULA_FILEPATH_A" ] && continue
    [ -L "$FORMULA_FILEPATH_B" ] && continue
    [ -f "$FORMULA_FILEPATH_B" ] || continue

    ################################################

    SHA256SUM_A="$(./xcpkg util sha256sum "$FORMULA_FILEPATH_A")"
    SHA256SUM_B="$(./xcpkg util sha256sum "$FORMULA_FILEPATH_B")"

    [ "$SHA256SUM_A" = "$SHA256SUM_B" ] && continue

    ################################################

    DIFF_CONTENT="$(diff "$FORMULA_FILEPATH_A" "$FORMULA_FILEPATH_B" || true)"

    [ -z "$DIFF_CONTENT" ] && continue

    DIFF_CONTENT2="$(printf '%s\n' "$DIFF_CONTENT" | grep '^[<>]' | sed 's|^[<>] ||')"

    cat <<EOF
diff $FORMULA_FILEPATH_A
$DIFF_CONTENT
EOF

    ################################################

    X=0

    export IFS='
'
    for LINE in $DIFF_CONTENT2
    do
        echo "LINE=$LINE"

        case $LINE in
            src-url:*|src-sha:*)
                ;;
            *)  X=1
                break
        esac
    done

    unset IFS

    [ "$X" = 1 ] && continue

    ################################################

    VERSION_A="$(./xcpkg formula-parse "$FORMULA_FILEPATH_A" version)"
    VERSION_B="$(./xcpkg formula-parse "$FORMULA_FILEPATH_B" version)"

    if version_match "$VERSION_B" gt "$VERSION_A" ; then
        mv "$FORMULA_FILEPATH_B" formula/ 

        FORMULA_FILENAME="${FORMULA_FILEPATH_A#formula/}"
        PACKAGE_NAME="${FORMULA_FILENAME%.yml}"

        if ./ndk-pkg install "android-35-arm64-v8a/$PACKAGE_NAME" ; then
            git add "$FORMULA_FILEPATH_A"
            git commit -m "github-actions-bot-auto-upgrade $FORMULA_FILEPATH_A $VERSION_A -> $VERSION_B"
            git push origin master
        else
            git checkout "$FORMULA_FILEPATH_A"
        fi
    fi
done

#########################################################################

run ls xcpkg-formula-repository-official-core/formula/
