#!/bin/sh

set -e

COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_BLUE='\033[0;94m'
COLOR_PURPLE='\033[0;35m'
COLOR_OFF='\033[0m'

printf_package_info_red() {
    printf "${COLOR_RED}%-20s %-15s %s${COLOR_OFF}\n" "$1" "$2" "$3"
}

printf_package_info_purple() {
    printf "${COLOR_PURPLE}%-20s %-15s %s${COLOR_OFF}\n" "$1" "$2" "$3"
}

printf_package_info_blue() {
    printf "${COLOR_BLUE}%-20s %-15s %s${COLOR_OFF}\n" "$1" "$2" "$3"
}

printf_package_info_green() {
    printf "${COLOR_GREEN}%-20s %-15s %s${COLOR_OFF}\n" "$1" "$2" "$3"
}

version_sort() {
    printf '%s\n' "$@" | sort -V
}

# check if match the condition
#
# condition:
# eq  equal
# ne  not equal
# gt  greater than
# lt  less than
# ge  greater than or equal
# le  less than or equal
#
# examples:
# version_match 1.15.3 eq 1.16.0
# version_match 1.15.3 lt 1.16.0
# version_match 1.15.3 gt 1.16.0
# version_match 1.15.3 le 1.16.0
# version_match 1.15.3 ge 1.16.0
version_match() {
    case $2 in
        eq)  [ "$1"  = "$3" ] ;;
        ne)  [ "$1" != "$3" ] ;;
        le)
            if [ "$1" = "$3" ] ; then
                return 0
            fi
            [ "$1" = "$(version_sort "$1" "$3" | head -n 1)" ]
            ;;
        ge)
            if [ "$1" = "$3" ] ; then
                return 0
            fi
            [ "$1" = "$(version_sort "$1" "$3" | tail -n 1)" ]
            ;;
        lt)
            if [ "$1" = "$3" ] ; then
                return 1
            fi
            [ "$1" = "$(version_sort "$1" "$3" | head -n 1)" ]
            ;;
        gt)
            if [ "$1" = "$3" ] ; then
                return 1
            fi
            [ "$1" = "$(version_sort "$1" "$3" | tail -n 1)" ]
            ;;
        *)  printf '%s\n' "version_compare: $2: not supported operator." >&2
            return 1
    esac
}

#########################################################################

cd formula

for FORMULA_FILENAME in *.yml
do
    PACKAGE_NAME="${FORMULA_FILENAME%.yml}"

    PACKAGE_VERSION="$(../xcpkg formula-parse "$FORMULA_FILENAME" version)"
    PACKAGE_WEB_URL="$(../xcpkg formula-parse "$FORMULA_FILENAME" web-url)"

    S1="$(../brew-package-name "$PACKAGE_NAME")"
    S2=

    case $PACKAGE_NAME in
        lib*)  S2="${PACKAGE_NAME#lib}"  ;;
        *-dev) S2="${PACKAGE_NAME%-dev}" ;;
    esac

    for BREW_PACKAGE_NAME in $S1 "$PACKAGE_NAME" $S2
    do
        if brew info "$BREW_PACKAGE_NAME" --json > /dev/null 2>&1 ; then
            BREW_PACKAGE_VERS=$(brew info "$BREW_PACKAGE_NAME" --json | yq '.[0].versions.stable')

            if [ "$BREW_PACKAGE_VERS" = "$PACKAGE_VERSION" ] ; then
                continue 2
            fi

            if version_match "$BREW_PACKAGE_VERS" gt "$PACKAGE_VERSION" ; then
                case $BREW_PACKAGE_NAME in
                    lib*) X=lib ;;
                       *) X="$(printf '%.1s' "$BREW_PACKAGE_NAME")"
                esac

                printf_package_info_red "$PACKAGE_NAME" "$PACKAGE_VERSION" "$PACKAGE_WEB_URL"
                printf_package_info_red "$BREW_PACKAGE_NAME" "$BREW_PACKAGE_VERS" "https://github.com/Homebrew/homebrew-core/blob/master/Formula/$X/$BREW_PACKAGE_NAME.rb"

                URL=$(brew info "$BREW_PACKAGE_NAME" --json | yq '.[0].urls.stable.url')
                SHA=$(brew info "$BREW_PACKAGE_NAME" --json | yq '.[0].urls.stable.checksum')

                if [ -n "$URL" ] && [ -n "$SHA" ] ; then
                    gsed -i -e "/^src-url: /c src-url: $URL" -e "/^src-sha: /c src-sha: $SHA" "$FORMULA_FILENAME"

                    if ../xcpkg install "$PACKAGE_NAME" ; then
                        git add "$FORMULA_FILENAME"
                        git commit -m "github-actions : update package $PACKAGE_NAME $PACKAGE_VERSION -> $BREW_PACKAGE_VERS"
                        git push origin master
                    else
                        git checkout "$FORMULA_FILENAME"
                    fi
                fi

                continue 2
            fi
        fi
    done

    PACKAGE_GIT_URL="$(../xcpkg formula-parse "$FORMULA_FILENAME" git-url)"

    case $PACKAGE_GIT_URL in
        https://github.com/*)
            X="${PACKAGE_GIT_URL#'https://github.com/'}"
            X="${X%/}"
            Y="${X%/*}"
            Z="${X#*/}"

            cat > QUERY <<EOF
            {
                repository(owner: "$Y", name: "$Z") {
                    latestRelease {
                      tagName
                    }
                }
            }
EOF

            LATEST_RELEASE_TAGNAME="$(gh api graphql -f "query=$(cat QUERY)" --jq .data.repository.latestRelease.tagName)"

            LATEST_RELEASE_VERSION="${LATEST_RELEASE_TAGNAME#v}"
            LATEST_RELEASE_VERSION="${LATEST_RELEASE_VERSION%-stable}"

            if version_match "$LATEST_RELEASE_VERSION" gt "$PACKAGE_VERSION" ; then
                printf_package_info_purple "$PACKAGE_NAME" "$PACKAGE_VERSION" "$PACKAGE_GIT_URL"
                printf_package_info_purple "$PACKAGE_NAME" "$LATEST_RELEASE_VERSION" "$PACKAGE_GIT_URL/releases/tag/$LATEST_RELEASE_TAGNAME"
            else
                printf_package_info_green  "$PACKAGE_NAME" "$PACKAGE_VERSION" "$PACKAGE_GIT_URL"
            fi

            printf '\n'

            continue
    esac

    printf_package_info_blue "$PACKAGE_NAME" "$PACKAGE_VERSION" "$PACKAGE_WEB_URL"
    printf '\n'
done
