summary "Maintained ctags implementation"
webpage "https://github.com/universal-ctags/ctags"
src_git "https://github.com/universal-ctags/ctags.git"
bsystem "autogen"
require "pkg-config"
depends "jansson libyaml libxml2"
