package set summary "GPU-accelerated terminal emulator"
package set webpage "https://alacritty.org/"
package set git.url "https://github.com/alacritty/alacritty.git"
package set src.url "https://github.com/alacritty/alacritty/archive/refs/tags/v0.10.1.tar.gz"
package set src.sum "e48d4b10762c2707bb17fd8f89bd98f0dcccc450d223cade706fdd9cfaefb308"
package set license "Apache-2.0"
package set bsystem "cargo"
