package set summary "Find visually similar or duplicate images"
package set git.url "https://gitlab.com/opennota/findimagedupes.git"
package set license "GPL-3.0"
package set dep.pkg "file libjpeg-turbo libpng libtiff"
package set bsystem "go"
