pkg_set summary "Framework for scientific data networking"
pkg_set webpage "https://www.opendap.org/"
pkg_set git.url "https://github.com/OPENDAP/libdap4.git"
pkg_set src.url "https://www.opendap.org/pub/source/libdap-3.20.8.tar.gz"
pkg_set src.sha "65eb5c8f693cf74d58eece5eaa2e7c3c65f368926b1bffab0cf5b207757b94eb"
pkg_set license "LGPL-2.1-or-later"
pkg_set dep.pkg "libxml2 curl util-linux"
pkg_set dep.cmd "pkg-config flex bison"
pkg_set bsystem "configure"
