package set summary "Code-search similar to ack"
package set git.url "https://github.com/ggreer/the_silver_searcher.git"
package set src.url "https://github.com/ggreer/the_silver_searcher/archive/2.2.0.tar.gz"
package set src.sum "6a0a19ca5e73b2bef9481c29a508d2413ca1a0a9a5a6b1bd9bbd695a7626cbf9"
package set license "Apache-2.0"
package set dep.pkg "pcre xz"
package set dep.cmd "pkg-config"
package set bsystem "autogen"
package set ccflags "-fcommon"
