package set summary "Automatic Language-Agnostic Subtitle Synchronization"
package set git.url "https://github.com/kaegi/alass.git"
package set license "GPL-3.0-or-later"
package set dep.pkg "ffmpeg"
package set bsystem "cargo"
package set bscript "alass-cli"
