package set summary "Tool for generating GNU Standards-compliant Makefiles"
package set webpage "https://www.gnu.org/software/automake"
package set src.url "https://ftp.gnu.org/gnu/automake/automake-1.16.3.tar.xz"
package set src.sum "ff2bf7656c4d1c6fdda3b8bebb21f09153a736bcba169aaf65eab25fa113bf3a"
package set license "GPL-2.0-or-later"
package set bsystem "configure"
package set dep.cmd "m4 perl"
