package set summary "New way to see and navigate directory trees"
package set webpage "https://dystroy.org/broot/"
package set git.url "https://github.com/Canop/broot.git"
package set src.url "https://github.com/Canop/broot/archive/v1.8.1.tar.gz"
package set src.sum "c806130c4982b064ccaa7fec79436af71d4cf06ace33c2cb34d4d30b3c1095e7"
package set license "MIT"
package set dep.pkg "zlib"
package set bsystem "cargo"
