package set summary "New way to see and navigate directory trees"
package set webpage "https://dystroy.org/broot/"
package set git.url "https://github.com/Canop/broot.git"
package set src.url "https://github.com/Canop/broot/archive/v1.10.0.tar.gz"
package set src.sum "0ec905b45dc58624e473e2b3f84951ab7afadde6dd9bdb72f190ab97e86af22d"
package set license "MIT"
package set dep.pkg "zlib"
package set bsystem "cargo"
