pkg_set summary "Converts books written in Markdown to HTML, LaTeX/PDF and EPUB"
pkg_set git.url "https://github.com/lise-henry/crowbook.git"
pkg_set src.url "https://github.com/lise-henry/crowbook/archive/refs/tags/v0.15.2e.tar.gz"
pkg_set src.sha "ac950c051faece985821c28c17206188a6211247a040a8e7afaa34a5f45cf81f"
pkg_set license "LGPL-2.1-or-later|LICENSE.md|https://raw.githubusercontent.com/lise-henry/crowbook/master/LICENSE.md"
pkg_set dep.pkg "openssl"
pkg_set bsystem "cargo"
