package set summary "Library to extract data from Excel .xls files"
package set webpage "https://www.gaia-gis.it/fossil/freexl/index"
package set src.url "https://www.gaia-gis.it/gaia-sins/freexl-sources/freexl-1.0.6.tar.gz"
package set src.sum "3de8b57a3d130cb2881ea52d3aa9ce1feedb1b57b7daa4eb37f751404f90fc22"
package set dep.pkg "libiconv"
package set bsystem "configure"
