pkg_set summary "Smart font renderer for non-Roman scripts"
pkg_set webpage "https://graphite.sil.org"
pkg_set git.url "https://github.com/silnrsi/graphite.git"
pkg_set src.url "https://github.com/silnrsi/graphite/releases/download/1.3.14/graphite2-1.3.14.tgz"
pkg_set src.sha "f99d1c13aa5fa296898a181dff9b82fb25f6cc0933dbaa7a475d8109bd54209d"
pkg_set license "LGPL-2.1-or-later|LICENSE|https://raw.githubusercontent.com/silnrsi/graphite/master/LICENSE"
pkg_set dep.pkg "freetype2"
pkg_set bsystem "cmake"
