pkg_set summary "Make JSON greppable"
pkg_set git.url "https://github.com/tomnomnom/gron.git"
pkg_set src.url "https://github.com/tomnomnom/gron/archive/v0.7.1.tar.gz"
pkg_set src.sha "1c98f2ef2ba03558864b1ab5e9c4b47a2e89d3ffaf24cfa0ac75cd38d775feb4"
pkg_set bsystem "go"
pkg_set license "MIT|LICENSE|https://raw.githubusercontent.com/tomnomnom/gron/master/LICENSE"
pkg_set developer "Tom+Hudson|mail@tomnomnom.com|Tom+Hudson|https://github.com/tomnomnom"
