package set summary "Make JSON greppable"
package set git.url "https://github.com/tomnomnom/gron.git"
package set src.url "https://github.com/tomnomnom/gron/archive/v0.7.1.tar.gz"
package set src.sum "1c98f2ef2ba03558864b1ab5e9c4b47a2e89d3ffaf24cfa0ac75cd38d775feb4"
package set bsystem "go"
package set license "MIT;LICENSE;https://raw.githubusercontent.com/tomnomnom/gron/master/LICENSE"
package set developer "Tom Hudson;mail@tomnomnom.com;sbtUK;https://github.com/tomnomnom"
