package set summary "Portable abstraction of the hierarchical topology of modern architectures"
package set webpage "https://www.open-mpi.org/projects/hwloc"
package set git.url "https://github.com/open-mpi/hwloc.git"
package set src.url "https://www.open-mpi.org/software/hwloc/v2.7/downloads/hwloc-2.7.0.tar.bz2"
package set src.sum "028cee53ebcfe048283a2b3e87f2fa742c83645fc3ae329134bf5bb8b90384e0"
package set license "BSD-3-Clause"
package set dep.pkg "libxml2"
package set bsystem "configure"
