package set summary "Portable abstraction of the hierarchical topology of modern architectures"
package set webpage "https://www.open-mpi.org/projects/hwloc"
package set src.git "https://github.com/open-mpi/hwloc.git"
package set src.url "https://www.open-mpi.org/software/hwloc/v2.6/downloads/hwloc-2.6.0.tar.bz2"
package set src.sum "e1f073e44e28c296ff848dead5e9bd6e2426b77f95ead1792358958e859fa83a"
package set license "BSD-3-Clause"
package set bsystem "configure"
package set dep.pkg "libxml2"
