pkg_set summary "Portable abstraction of the hierarchical topology of modern architectures"
pkg_set webpage "https://www.open-mpi.org/projects/hwloc"
pkg_set git.url "https://github.com/open-mpi/hwloc.git"
pkg_set src.url "https://www.open-mpi.org/software/hwloc/v2.7/downloads/hwloc-2.7.0.tar.bz2"
pkg_set src.sha "028cee53ebcfe048283a2b3e87f2fa742c83645fc3ae329134bf5bb8b90384e0"
pkg_set license "BSD-3-Clause;COPYING;https://raw.githubusercontent.com/open-mpi/hwloc/master/COPYING"
pkg_set dep.pkg "libxml2"
pkg_set bsystem "configure"
