package set summary "Image processing and image analysis library"
package set webpage "http://www.leptonica.org/"
package set git.url "https://github.com/DanBloomberg/leptonica.git"
package set src.url "http://www.leptonica.org/source/leptonica-1.82.0.tar.gz"
package set src.sum "155302ee914668c27b6fe3ca9ff2da63b245f6d62f3061c8f27563774b8ae2d6"
package set license "BSD-2-Clause"
package set dep.pkg "libwebp openjpeg"
package set dep.cmd "pkg-config"
package set bsystem "configure"
