pkg_set summary "a password hashing method based on the Blowfish block cipher, provided via the crypt(3) and a reentrant interface."
pkg_set webpage "https://www.openwall.com/crypt"
pkg_set git.url "https://github.com/leleliu008/libbcrypt.git"
pkg_set license "CC0-1.0"
pkg_set bsystem "cmake"
