pkg_set summary "Asynchronous event library"
pkg_set webpage "http://software.schmorp.de/pkg/libev.html"
pkg_set src.url "https://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/libe/libev/libev_4.33.orig.tar.gz"
pkg_set src.sha "507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea"
pkg_set license ";LICENSE;http://cvs.schmorp.de/libev/LICENSE"
pkg_set bsystem "configure"
