pkg_set summary "glob(3) implementation"
pkg_set webpage "https://linux.die.net/man/3/glob"
pkg_set git.url "https://github.com/leleliu008/libglob.git"
pkg_set license ";LICENSE;https://raw.githubusercontent.com/leleliu008/libglob/master/LICENSE"
pkg_set bsystem "cmake"
