pkg_set summary "Library and utility to talk to iBoot/iBSS via USB"
pkg_set webpage "https://www.libimobiledevice.org"
pkg_set git.url "https://github.com/libimobiledevice/libirecovery.git"
pkg_set src.url "https://github.com/libimobiledevice/libirecovery/releases/download/1.0.0/libirecovery-1.0.0.tar.bz2"
pkg_set src.sha "cda0aba10a5b6fc2e1d83946b009e3e64d0be36912a986e35ad6d34b504ad9b4"
pkg_set license "LGPL-2.1-only"
pkg_set dep.pkg "libusb readline"
pkg_set bsystem "configure"
pkg_set ldflags "-lncurses"
