pkg_set summary "Packaged version of iLBC codec from the WebRTC project"
pkg_set git.url "https://github.com/TimothyGu/libilbc.git"
pkg_set src.url "https://github.com/TimothyGu/libilbc/releases/download/v3.0.4/libilbc-3.0.4.tar.gz"
pkg_set src.sha "6820081a5fc58f86c119890f62cac53f957adb40d580761947a0871cea5e728f"
pkg_set bsystem "cmake"
pkg_set license "BSD-3-Clause|COPYING|https://raw.githubusercontent.com/TimothyGu/libilbc/main/COPYING"
pkg_set developer "WebRTC+project+authors;;WebRTC;https://webrtc.org/"
