pkg_set summary "C/C++ seam carving library"
pkg_set webpage "https://liblqr.wikidot.com/"
pkg_set git.url "https://github.com/carlobaldassi/liblqr.git"
pkg_set src.url "https://github.com/carlobaldassi/liblqr/archive/v0.4.2.tar.gz"
pkg_set src.sha "1019a2d91f3935f1f817eb204a51ec977a060d39704c6dafa183b110fd6280b0"
pkg_set license "LGPL-3.0-or-later;COPYING;https://raw.githubusercontent.com/carlobaldassi/liblqr/master/COPYING"
pkg_set dep.pkg "glib"
pkg_set dep.cmd "pkg-config"
pkg_set bsystem "configure"
