package set summary "C/C++ seam carving library"
package set webpage "https://liblqr.wikidot.com/"
package set git.url "https://github.com/carlobaldassi/liblqr.git"
package set src.url "https://github.com/carlobaldassi/liblqr/archive/v0.4.2.tar.gz"
package set src.sum "1019a2d91f3935f1f817eb204a51ec977a060d39704c6dafa183b110fd6280b0"
package set license "LGPL-3.0-or-later;COPYING;https://raw.githubusercontent.com/carlobaldassi/liblqr/master/COPYING"
package set dep.pkg "glib"
package set dep.cmd "pkg-config"
package set bsystem "configure"
