pkg_set summary "Library for manipulating PNG images"
pkg_set webpage "http://www.libpng.org/pub/png/libpng.html"
pkg_set git.url "https://github.com/glennrp/libpng.git"
pkg_set src.url "https://downloads.sourceforge.net/libpng/libpng-1.6.37.tar.xz"
pkg_set src.sha "505e70834d35383537b6491e7ae8641f1a4bed1876dbfe361201fc80868d88ca"
pkg_set dep.pkg "zlib"
pkg_set bsystem "configure"
pkg_set license "libpng-2.0|LICENSE|https://raw.githubusercontent.com/glennrp/libpng/libpng16/LICENSE"
pkg_set developer "PNG+REFERENCE+LIBRARY+AUTHORS;;PNG+REFERENCE+LIBRARY+AUTHORS;http://www.libpng.org/pub/png/src/libpng-AUTHORS.txt"
