pkg_set summary "Library for Qalculate! program"
pkg_set webpage "https://qalculate.github.io/"
pkg_set git.url "https://github.com/Qalculate/libqalculate.git"
pkg_set src.url "https://github.com/Qalculate/libqalculate/releases/download/v4.2.0/libqalculate-4.2.0.tar.gz"
pkg_set src.sha "2b86e656508f0b1c55236b08fd579b676563e1500b3db8304580de69c5693e4b"
pkg_set license "GPL-2.0-or-later"
pkg_set dep.cmd "pkg-config intltoolize xgettext"
pkg_set dep.plm "XML::Parser"
pkg_set dep.pkg "gettext readline icu4c libxml2 curl gmp mpfr libbthread"
pkg_set ccflags "-include pthread.h -include bthread.h -lbthread"
pkg_set bsystem "configure"
