package set summary "Library for Qalculate! program"
package set webpage "https://qalculate.github.io/"
package set git.url "https://github.com/Qalculate/libqalculate.git"
package set src.url "https://github.com/Qalculate/libqalculate/releases/download/v4.1.1/libqalculate-4.1.1.tar.gz"
package set src.sum "b5611a91293be40fbe8723a81937e25ffb54e6ad6e60f282d044ed92f2d97002"
package set license "GPL-2.0-or-later"
package set dep.cmd "pkg-config intltoolize xgettext"
package set dep.plm "XML::Parser"
package set dep.pkg "gettext readline icu4c libxml2 curl gmp mpfr libbthread"
package set ccflags "-include pthread.h -include bthread.h -lbthread"
package set bsystem "configure"
