package set summary "Library for Qalculate! program"
package set webpage "https://qalculate.github.io/"
package set git.url "https://github.com/Qalculate/libqalculate.git"
package set src.url "https://github.com/Qalculate/libqalculate/releases/download/v4.1.0/libqalculate-4.1.0.tar.gz"
package set src.sum "d943e5285bdc0b3cd77b8f7a10391d7c753fc19b0ddd48e5d4179decf709d6ff"
package set license "GPL-2.0-or-later"
package set dep.cmd "pkg-config intltoolize xgettext"
package set dep.plm "XML::Parser"
package set dep.pkg "gettext readline icu4c libxml2 curl gmp mpfr libbthread"
package set ccflags "-include pthread.h -include bthread.h -lbthread"
package set bsystem "configure"
