pkg_set summary "Library to store and retrieve huge raster coverages"
pkg_set webpage "https://www.gaia-gis.it/fossil/librasterlite/index"
pkg_set src.url "https://www.gaia-gis.it/gaia-sins/librasterlite-sources/librasterlite-1.1g.tar.gz"
pkg_set src.sha "0a8dceb75f8dec2b7bd678266e0ffd5210d7c33e3d01b247e9e92fa730eebcb3"
pkg_set license "MPL-1.1"
pkg_set dep.pkg "libgeotiff libspatialite libpng"
pkg_set dep.cmd "pkg-config"
pkg_set bsystem "configure"
