package set summary "Small library for rendering Postscript documents"
package set webpage "https://wiki.freedesktop.org/www/Software/libspectre/"
package set src.git "https://gitlab.freedesktop.org/libspectre/libspectre.git"
package set src.url "https://libspectre.freedesktop.org/releases/libspectre-0.2.9.tar.gz"
package set src.sum "49ae9c52b5af81b405455c19fe24089d701761da2c45d22164a99576ceedfbed"
package set license "GPL-2.0-or-later"
package set dep.pkg "ghostscript"
package set dep.cmd "pkg-config"
package set bsystem "configure"
package set binsrcd "yes"
