package set summary "Small library for rendering Postscript documents"
package set webpage "https://wiki.freedesktop.org/www/Software/libspectre/"
package set git.url "https://gitlab.freedesktop.org/libspectre/libspectre.git"
package set src.url "https://libspectre.freedesktop.org/releases/libspectre-0.2.10.tar.gz"
package set src.sum "cf60b2a80f6bfc9a6b110e18f08309040ceaa755210bf94c465a969da7524d07"
package set license "GPL-2.0-or-later"
package set dep.pkg "ghostscript"
package set dep.cmd "pkg-config"
package set bsystem "configure"
package set binbstd "yes"
