pkg_set summary "Small library for rendering Postscript documents"
pkg_set webpage "https://wiki.freedesktop.org/www/Software/libspectre/"
pkg_set git.url "https://gitlab.freedesktop.org/libspectre/libspectre.git"
pkg_set src.url "https://libspectre.freedesktop.org/releases/libspectre-0.2.10.tar.gz"
pkg_set src.sha "cf60b2a80f6bfc9a6b110e18f08309040ceaa755210bf94c465a969da7524d07"
pkg_set license "GPL-2.0-or-later"
pkg_set dep.pkg "ghostscript"
pkg_set dep.cmd "pkg-config"
pkg_set bsystem "configure"
pkg_set binbstd "yes"
