pkg_set summary "Thai language support library"
pkg_set webpage "https://linux.thai.net/projects/libthai"
pkg_set git.url "https://github.com/tlwg/libthai.git"
pkg_set src.url "https://github.com/tlwg/libthai/releases/download/v0.1.28/libthai-0.1.28.tar.xz"
pkg_set src.sha "ffe0a17b4b5aa11b153c15986800eca19f6c93a4025ffa5cf2cab2dcdf1ae911"
pkg_set license "LGPL-2.1-or-later;COPYING;https://raw.githubusercontent.com/tlwg/libthai/master/COPYING"
pkg_set dep.pkg "libdatrie"
pkg_set dep.cmd "trietool"
pkg_set bsystem "configure"
