package set summary "Thai language support library"
package set webpage "https://linux.thai.net/projects/libthai"
package set src.git "https://github.com/tlwg/libthai.git"
package set src.url "https://github.com/tlwg/libthai/releases/download/v0.1.28/libthai-0.1.28.tar.xz"
package set src.sum "ffe0a17b4b5aa11b153c15986800eca19f6c93a4025ffa5cf2cab2dcdf1ae911"
package set dep.cmd "trietool"
package set dep.pkg "libdatrie"
package set bsystem "configure"
