package set summary "Image format providing lossless and lossy compression for web images"
package set webpage "https://developers.google.com/speed/webp"
package set git.url "https://chromium.googlesource.com/webm/libwebp.git"
package set src.url "http://downloads.webmproject.org/releases/webp/libwebp-1.2.2.tar.gz"
package set src.sum "7656532f837af5f4cec3ff6bafe552c044dc39bf453587bd5b77450802f4aee6"
package set license "BSD-3-Clause"
package set dep.pkg "libpng libtiff libjpeg-turbo giflib"
package set dep.cmd "pkg-config"
package set bsystem "cmake"
