pkg_set summary "Image format providing lossless and lossy compression for web images"
pkg_set webpage "https://developers.google.com/speed/webp"
pkg_set git.url "https://github.com/webmproject/libwebp.git"
pkg_set src.url "http://downloads.webmproject.org/releases/webp/libwebp-1.2.2.tar.gz"
pkg_set src.sha "7656532f837af5f4cec3ff6bafe552c044dc39bf453587bd5b77450802f4aee6"
pkg_set license "BSD-3-Clause;COPYING;https://raw.githubusercontent.com/webmproject/libwebp/main/COPYING"
pkg_set dep.pkg "libpng libtiff libjpeg-turbo giflib"
pkg_set dep.cmd "pkg-config"
pkg_set bsystem "cmake"
