pkg_set summary "Unified display of technical and tag data for audio/video"
pkg_set webpage "https://mediaarea.net"
pkg_set src.url "https://mediaarea.net/download/source/mediainfo/22.06/mediainfo_22.06.tar.bz2"
pkg_set src.sha "9ccb156787bae78cd303f0979e074ab64811bc7cbd3c49db9a3961cfb841d81e"
pkg_set license "BSD-2-Clause"
pkg_set dep.cmd "pkg-config glibtoolize:libtoolize"
pkg_set dep.pkg "libmediainfo"
pkg_set bscript "Project/GNU/CLI"
pkg_set bsystem "autogen"
pkg_set binbstd "yes"
