package set summary "C library for zip/unzip via zLib"
package set webpage "https://www.winimage.com/zLibDll/minizip.html"
package set src.url "https://zlib.net/zlib-1.2.11.tar.gz"
package set src.sum "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1"
package set license "Zlib"
package set dep.cmd "libtoolize"
package set sourced "contrib/minizip"
package set bsystem "autotools"
