package set summary "Library like getopt(3) with a number of enhancements"
package set src.git "https://github.com/rpm-software-management/popt.git"
package set src.url "http://ftp.rpm.org/popt/releases/popt-1.x/popt-1.18.tar.gz"
package set src.sum "5159bc03a20b28ce363aa96765f37df99ea4d8850b1ece17d1e6ad5c24fdc5d1"
package set license "MIT"
package set bsystem "configure"
package set dep.pkg "libglob"
package set ldflags "-lglob"
