pkg_set summary "Cartographic Projections Library"
pkg_set webpage "https://proj.org/"
pkg_set git.url "https://github.com/OSGeo/PROJ.git"
pkg_set src.url "https://github.com/OSGeo/PROJ/releases/download/9.0.1/proj-9.0.1.tar.gz"
pkg_set src.sha "737eaacbe7906d0d6ff43f0d9ebedc5c734cccc9e6b8d7beefdec3ab22d9a6a3"
pkg_set license "MIT"
pkg_set dep.pkg "libtiff curl sqlite nlohmann-json"
pkg_set dep.cmd "sqlite3"
pkg_set bsystem "cmake"
