package set summary "Experimental Rust compiler front-end for IDEs"
package set webpage "https://rust-analyzer.github.io/"
package set git.url "https://github.com/rust-analyzer/rust-analyzer.git"
package set version "2022-02-07"
package set src.url "https://github.com/rust-analyzer/rust-analyzer/archive/refs/tags/$PACKAGE_VERSION.tar.gz"
package set src.sum "e5c5e91125d1b47530ce380965de806c468d93e38e0de9328cdf29878f70be30"
package set license "Apache-2.0"
package set sourced "crates/rust-analyzer"
package set bsystem "cargo"
