package set summary "Experimental Rust compiler front-end for IDEs"
package set webpage "https://rust-analyzer.github.io/"
package set git.url "https://github.com/rust-analyzer/rust-analyzer.git"
package set version "2022-03-07"
package set src.url "https://github.com/rust-analyzer/rust-analyzer/archive/refs/tags/$PACKAGE_VERSION.tar.gz"
package set src.sum "f5b88b0beeec070af3d4e856ee04eb65bf110034982dcca5b216f85d7cb9395a"
package set license "Apache-2.0"
package set sourced "crates/rust-analyzer"
package set bsystem "cargo"
