package set summary "Experimental Rust compiler front-end for IDEs"
package set webpage "https://rust-analyzer.github.io/"
package set git.url "https://github.com/rust-analyzer/rust-analyzer.git"
package set version "2022-01-10"
package set src.url "https://github.com/rust-analyzer/rust-analyzer/archive/refs/tags/$PACKAGE_VERSION.tar.gz"
package set src.sum "dec14ac0427676d09182a5363a15e84cd3c906dbe81d60889d64d92cd96d37d2"
package set license "Apache-2.0"
package set sourced "crates/rust-analyzer"
package set bsystem "cargo"
