pkg_set summary "Audio processing library"
pkg_set webpage "https://www.surina.net/soundtouch/"
pkg_set git.url "https://codeberg.org/soundtouch/soundtouch.git"
pkg_set src.url "https://www.surina.net/soundtouch/soundtouch-2.3.1.tar.gz"
pkg_set src.sha "6900996607258496ce126924a19fe9d598af9d892cf3f33d1e4daaa9b42ae0b1"
pkg_set license "LGPL-2.1-or-later|COPYING.TXT|https://codeberg.org/soundtouch/soundtouch/raw/branch/master/COPYING.TXT"
pkg_set dep.cmd "glibtoolize:libtoolize"
pkg_set bsystem "autotools"
