package set summary "Speex audio processing library"
package set git.url "https://github.com/xiph/speexdsp.git"
package set src.url "https://github.com/xiph/speexdsp/archive/SpeexDSP-1.2.0.tar.gz"
package set src.sum "d7032f607e8913c019b190c2bccc36ea73fc36718ee38b5cdfc4e4c0a04ce9a4"
package set license "BSD-3-Clause;COPYING;https://raw.githubusercontent.com/xiph/speexdsp/master/COPYING"
package set dep.cmd "glibtoolize:libtoolize"
package set bsystem "autogen"
package set ldflags "-lm"
