pkg_set summary "Audio codec designed for speech"
pkg_set webpage "https://speex.org"
pkg_set git.url "https://github.com/xiph/speex.git"
pkg_set src.url "https://github.com/xiph/speex/archive/refs/tags/Speex-1.2.1.tar.gz"
pkg_set src.sha "beaf2642e81a822eaade4d9ebf92e1678f301abfc74a29159c4e721ee70fdce0"
pkg_set license "BSD-3-Clause|COPYING|https://raw.githubusercontent.com/xiph/speex/master/COPYING"
pkg_set dep.pkg "libogg speexdsp"
pkg_set dep.cmd "pkg-config"
pkg_set bsystem "autogen"
