pkg_set summary "Implementation of extended-Rice lossless compression algorithm"
pkg_set webpage "https://support.hdfgroup.org/HDF5/release/obtain5.html#extlibs"
pkg_set src.url "https://support.hdfgroup.org/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz"
pkg_set src.sha "21ee958b4f2d4be2c9cabfa5e1a94877043609ce86fde5f286f105f7ff84d412"
pkg_set license ";COPYING;https://support.hdfgroup.org/doc_resource/SZIP/Commercial_szip.html"
pkg_set bsystem "configure"
