package set summary "C test project"
package set git.url "https://github.com/leleliu008/C.git"
package set src.url "dir:///Users/leleliu008/git/C"
package set src.url "dir:///home/fpliu/cmake-test"
package set bsystem "cmake"
