package set summary "C test project"
package set src.git "https://github.com/leleliu008/C.git"
package set src.url "dir:///Users/leleliu008/git/C"
package set src.url "dir:///home/fpliu/cmake-test"
package set dep.cmd "ninja>=1.10.2"
package set bsystem "cmake"
