package set summary "TOML config file parser and serializer for C++"
package set webpage "https://marzer.github.io/tomlplusplus/"
package set src.git "https://github.com/marzer/tomlplusplus.git"
package set src.url "https://github.com/marzer/tomlplusplus/archive/refs/tags/v2.5.0.tar.gz"
package set src.sum "2e246ee126cfb7bd68edd7285d5bb5c8c5296121ce809306ee71cfd6127c76a6"
package set license "MIT"
package set bsystem "cmake"
