package set summary "Maintained ctags implementation"
package set git.url "https://github.com/universal-ctags/ctags.git"
package set bsystem "autogen"
package set dep.cmd "pkg-config"
package set dep.pkg "jansson libyaml libxml2"
