name: build changed packages

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:

  find-changed-packages:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: 'formula/*.yml'
          json: true

      - id: changed-packages
        run: |
          NAMES=$(printf '%s\n' ${{ steps.changed-files.outputs.all_changed_files }} | jq -c '
            map(
              sub("^formula/"; "")
              | sub("\\.yml$"; "")
            )
          ')
          printf 'names=%s\n' "$NAMES" >> $GITHUB_OUTPUT

    outputs:
      names: ${{ steps.changed-packages.outputs.names }}


  ubuntu:

    needs: find-changed-packages

    if: needs.find-changed-packages.outputs.names != '[]'

    strategy:

      fail-fast: false

      matrix:
        abi: [arm64-v8a]
        opt: ['--static', '']
        pkg: ${{ fromJson(needs.find-changed-packages.outputs.names) }}

    runs-on: ubuntu-latest

    container: ubuntu:24.04

    steps:
      - uses: actions/checkout@v5

      - run: apt -y update
      - run: apt -y install curl

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}


  alpine:

    needs: find-changed-packages

    if: needs.find-changed-packages.outputs.names != '[]'

    strategy:

      fail-fast: false

      matrix:
        abi: [arm64-v8a]
        opt: ['--static', '']
        pkg: ${{ fromJson(needs.find-changed-packages.outputs.names) }}

    runs-on: ubuntu-latest

    container: alpine

    steps:
      - uses: actions/checkout@v5

      - run: wget https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}


  macos:

    needs: find-changed-packages

    if: needs.find-changed-packages.outputs.names != '[]'

    strategy:

      fail-fast: false

      matrix:
        os:  [macos-26, macos-15]
        abi: [arm64-v8a]
        opt: ['--static', '']
        pkg: ${{ fromJson(needs.find-changed-packages.outputs.names) }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}
