name: check if urls are alive

on:
  workflow_dispatch:

  schedule:
    - cron: '0 22 * * *'

jobs:
  check:

    runs-on: ubuntu-latest

    container: ubuntu:24.04

    steps:
      - uses: actions/checkout@v5

      - run: |
            cat > .ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ndk-pkg-formula-repository-official-core
            branch: master
            pinned: 0
            enabled: 1
            created: 1673684639
            EOF

      - run: install -d ~/.ndk-pkg/repos.d/
      - run: ln -s ${{ github.workspace }} ~/.ndk-pkg/repos.d/
      - run: ls ~/.ndk-pkg/repos.d/

      - run: apt -y update
      - run: apt -y install curl

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo

      - run: |
          cd formula

          for f in *.yml
          do
              PACKAGE_NAME="${f%.yml}"
              printf '\n%b\n' "\033[0;31m==> $$PACKAGE_NAME\033[0m"
              ../ndk-pkg fetch "$$PACKAGE_NAME"
          done
